STRUCTURE_THRESHOLD          = 0.28
STAR_THRESHOLD               = 0.28
TECHNICAL_TERM_DENSITY_FLOOR = 0.04
COMPLETENESS_LENGTH_FLOOR    = 30
DEPTH_MIN_SENTENCES          = 2
DEPTH_DIVERSITY_WEIGHT       = 0.55
DEPTH_TECHNICAL_WEIGHT       = 0.45